version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'spring'
      POSTGRES_PASSWORD: '123'
  backend:
    image: registry.gitlab.com/renti-software/backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  react:
    build: 
      context: .
      args:
        REACT_APP_API_IP: 'localhost'
    ports:
      - "3000:3000"
    depends_on:
      - backend
