version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: registry.gitlab.com/tqs-project/backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  react:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
